version: "3"
services:
  tiktok:
    build:
      context: .
      dockerfile: Dockerfile.tiktok
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
